name: dbt-metabase
run-name: GitHub Actions will sync descriptions/metadata from dbt with Metabase
on: [push]
jobs:
  run-dbt-metabase:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4.2.0
       with:
         python-version: '3.10' 
     - run: pip install dbt-metabase
